[project]
name = "mongodb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bson>=0.5.10",
    "mcp[cli]>=1.6.0",
    "pymongo>=4.12.0",
]
