servers:
  playwright:
    params:
      command: npx
      args: ["-y", "@playwright/mcp@latest"]
      env: {}
    cache_tools_list: true

  localSearch:
    params:
      command: uv
      args: ["run", "../MCP/localsearch/main.py"]
      env: {}
    cache_tools_list: true

  filesystem:
    params:
      command: uv
      args: ["run", "../MCP/filesystem/main.py"]
      env: {}
    cache_tools_list: true
    
  mongodb:
    params:
      command: uv
      args: ["run", "../MCP/mongodb/main.py"]
      env:
        MCP_MONGODB_URI: "mongodb://localhost:27017/family"
        MCP_MONGODB_READONLY: "false"
    cache_tools_list: true

  # 可以添加更多的 server 配置
  # another_server:
  #   params:
  #     command: ...
  #     args: [...]
  #     env: {}
  #   cache_tools_list: true 