servers:
  playwright:
    params:
      command: npx
      args: ["-y", "@playwright/mcp@latest"]
    cache_tools_list: true

  localSearch:
    params:
      command: uv
      args: ["run", "--directory", "../MCP/localsearch", "main.py"]
    cache_tools_list: true

  filesystem:
    params:
      command: uv
      args: ["run", "--directory", "../MCP/filesystem", "main.py"]
    cache_tools_list: true

  mongodb:
    params:
      command: uv
      args: ["run", "--directory", "../MCP/mongodb", "main.py", "--uri", "mongodb://localhost:27017/family", "--read-only"]
    cache_tools_list: true

  # 可以添加更多的 server 配置
  # another_server:
  #   params:
  #     command: ...
  #     args: [...]
  #   cache_tools_list: true 